### ISSUE TITLE
Feature request: normalize folder naming

### ISSUE THREAD

**Issue by Jackymancs4** [Davis24/video-game-text-dataset#1]
Hello @Davis24 
Big fan of your work on https://libraryofcodexes.com/ since I found it a couple years ago looking for an epub of all Skyim books. I read most of the other books since then.

It's great to see this new effort of yours publishing all that content in a machine-friendly format.

Anyway, navigating through the content of the repo in bash is a little annoying because of the names containing spaces, so I suggest that the folders names in `series` and theirs inner files become snake_cased eg. `star wars the old republic` to `star_wars_the_old_republic`

Thank you!

**Comment by Davis24** [comment]
Folder names have been normalized in the most recent push
