### ISSUE TITLE
Use string as id type

### ISSUE THREAD

**Issue by Jackymancs4** [Davis24/video-game-text-dataset#4]
I have not really found docs on this (except some issues here and there), so if there are technical constraints to this just close the issue, but as a rule of thumb string is a preffered type for ids because `{"id" : 00001 }` and `{"id" : 1 }` points to the same resource once parsed while `{"id" : "00001" }` and `{"id" : "1" }` do not.

The less ambiguity, the better.

**Comment by Davis24** [comment]
Sounds good, I'll make the change and push in the next commit.

**Comment by Davis24** [comment]
Newest push updated all .jsons to have id as a string
